# Generated by Django 5.2.12 on 2026-03-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group_code',
            field=models.CharField(default='UNSET', max_length=64),
        ),
    ]
