# Generated by Django 5.2.12 on 2026-03-27 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_student_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='title',
        ),
        migrations.AddField(
            model_name='question',
            name='text_kk',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='text_ru',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='text_uz',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='survey',
            name='title_kk',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='survey',
            name='title_ru',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='survey',
            name='title_uz',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_option',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Красный — плохо'), (2, 'Желтый — нормально'), (3, 'Зеленый — хорошо')]),
        ),
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psychologist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='surveys.psychologist'),
        ),
    ]
