# Generated by Django 5.0.1 on 2026-03-28 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_remove_question_text_remove_survey_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uz', models.CharField(default='', max_length=255)),
                ('text_kk', models.CharField(default='', max_length=255)),
                ('text_ru', models.CharField(default='', max_length=255)),
                ('value', models.PositiveSmallIntegerField(choices=[(1, 'Красный'), (2, 'Жёлтый'), (3, 'Зелёный')])),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='surveys.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.option'),
        ),
    ]
